field_translation_balance_sheet = {
    "Treasury Shares Number": "Número de Ações em Tesouraria",
    "Ordinary Shares Number": "Número de Ações Ordinárias",
    "Share Issued": "Ações Emitidas",
    "Net Debt": "Dívida Líquida",
    "Total Debt": "Dívida Total",
    "Tangible Book Value": "Valor Contábil Tangível",
    "Invested Capital": "Capital Investido",
    "Working Capital": "Capital de Giro",
    "Net Tangible Assets": "Ativo Tangível Líquido",
    "Capital Lease Obligations": "Obrigações de Arrendamento Capital",
    "Common Stock Equity": "Patrimônio Líquido das Ações Ordinárias",
    "Total Capitalization": "Capitalização Total",
    "Stockholders Equity": "Patrimônio Líquido dos Acionistas",
    "Other Equity Interest": "Outros Interesses Patrimoniais",
    "Treasury Stock": "Ações em Tesouraria",
    "Capital Stock": "Capital Social",
    "Common Stock": "Ações Ordinárias",
    "Total Liabilities": "Passivo Total",
    "Total Non Current Liabilities Net Minority Interest": "Total de Passivos Não Correntes Líquidos de Participações Minoritárias",
    "Other Non Current Liabilities": "Outros Passivos Não Correntes",
    "Trade and Other Payables Non Current": "Contas a Pagar Não Correntes e Outros",
    "Non Current Deferred Revenue": "Receita Diferida Não Corrente",
    "Non Current Deferred Taxes Liabilities": "Obrigações de Impostos Diferidos Não Correntes",
    "Long Term Debt And Capital Lease Obligation": "Dívida de Longo Prazo e Obrigações de Arrendamento Capital",
    "Long Term Capital Lease Obligation": "Obrigações de Arrendamento Capital de Longo Prazo",
    "Long Term Debt": "Dívida de Longo Prazo",
    "Current Liabilities": "Passivos Correntes",
    "Other Current Liabilities": "Outros Passivos Correntes",
    "Current Debt And Capital Lease Obligation": "Dívida Corrente e Obrigações de Arrendamento Capital",
    "Current Capital Lease Obligation": "Obrigações de Arrendamento Capital Corrente",
    "Current Debt": "Dívida Corrente",
    "Payables": "Contas a Pagar",
    "Other Payable": "Outros Credores",
    "Dividends Payable": "Dividendos a Pagar",
    "Total Tax Payable": "Imposto Total a Pagar",
    "Accounts Payable": "Contas a Pagar",
    "Total Assets": "Ativo Total",
    "Non Current Assets": "Ativo Não Circulante",
    "Other Non Current Assets": "Outros Ativos Não Correntes",
    "Non Current Deferred Taxes Assets": "Ativos de Impostos Diferidos Não Correntes",
    "Investment in Financial Assets": "Investimentos em Ativos Financeiros",
    "Trading Securities": "Títulos para Negociação",
    "Long Term Equity Investment": "Investimento em Ações de Longo Prazo",
    "Investments in Joint Ventures at Cost": "Investimentos em Joint Ventures pelo Custo",
    "Investments in Subsidiaries at Cost": "Investimentos em Subsidiárias pelo Custo",
    "Goodwill And Other Intangible Assets": "Goodwill e Outros Ativos Intangíveis",
    "Other Intangible Assets": "Outros Ativos Intangíveis",
    "Goodwill": "Goodwill",
    "Net PPE": "Ativo Imobilizado Líquido",
    "Accumulated Depreciation": "Depreciação Acumulada",
    "Gross PPE": "Ativo Imobilizado Bruto",
    "Construction In Progress": "Construção em Andamento",
    "Other Properties": "Outros Imóveis",
    "Machinery Furniture Equipment": "Máquinas, Móveis e Equipamentos",
    "Buildings And Improvements": "Edifícios e Melhorias",
    "Properties": "Propriedades",
    "Current Assets": "Ativos Correntes",
    "Other Current Assets": "Outros Ativos Correntes",
    "Inventories": "Estoques",
    "Inventories Adjustments Allowances": "Ajustes de Estoques",
    "Finished Goods": "Produtos Acabados",
    "Raw Materials": "Matérias-Primas",
    "Other Receivables": "Outras Contas a Receber",
    "Taxes Receivable": "Impostos a Receber",
    "Accounts Receivable": "Contas a Receber",
    "Cash Cash Equivalents And Short Term Investments": "Caixa, Equivalentes de Caixa e Investimentos de Curto Prazo",
    "Other Short Term Investments": "Outros Investimentos de Curto Prazo",
    "Cash And Cash Equivalents": "Caixa e Equivalentes de Caixa",
    "Cash Equivalents": "Equivalentes de Caixa",
    "Cash Financial": "Caixa Financeiro",
    "Total Non Current Assets": "Ativos Não Corrente",
}

field_translation_cashflow = {
    "Free Cash Flow": "Fluxo de Caixa Livre",
    "Repurchase Of Capital Stock": "Recompra de Ações",
    "Repayment Of Debt": "Pagamento de Dívida",
    "Issuance Of Debt": "Emissão de Dívida",
    "Issuance Of Capital Stock": "Emissão de Ações",
    "Capital Expenditure": "Despesas de Capital",
    "End Cash Position": "Posição de Caixa Final",
    "Beginning Cash Position": "Posição de Caixa Inicial",
    "Changes In Cash": "Mudanças em Caixa",
    "Financing Cash Flow": "Fluxo de Caixa de Financiamento",
    "Net Other Financing Charges": "Encargos de Financiamento Líquidos",
    "Interest Paid Cff": "Juros Pagos",
    "Cash Dividends Paid": "Dividendos em Dinheiro Pagos",
    "Common Stock Dividend Paid": "Dividendos de Ações Ordinárias Pagos",
    "Net Common Stock Issuance": "Emissão Líquida de Ações Ordinárias",
    "Common Stock Payments": "Pagamentos de Ações Ordinárias",
    "Common Stock Issuance": "Emissão de Ações Ordinárias",
    "Net Issuance Payments Of Debt": "Pagamentos Líquidos de Emissão de Dívida",
    "Net Long Term Debt Issuance": "Emissão Líquida de Dívida de Longo Prazo",
    "Long Term Debt Payments": "Pagamentos de Dívida de Longo Prazo",
    "Long Term Debt Issuance": "Emissão de Dívida de Longo Prazo",
    "Investing Cash Flow": "Fluxo de Caixa de Investimento",
    "Net Business Purchase And Sale": "Compra e Venda Líquida de Negócios",
    "Sale Of Business": "Venda de Negócio",
    "Purchase Of Business": "Compra de Negócio",
    "Net Intangibles Purchase And Sale": "Compra e Venda Líquida de Intangíveis",
    "Sale Of Intangibles": "Venda de Intangíveis",
    "Purchase Of Intangibles": "Compra de Intangíveis",
    "Net PPE Purchase And Sale": "Compra e Venda Líquida de Ativo Imobilizado",
    "Purchase Of PPE": "Compra de Ativo Imobilizado",
    "Operating Cash Flow": "Fluxo de Caixa Operacional",
    "Taxes Refund Paid": "Reembolso de Impostos Pagos",
    "Dividend Received Cfo": "Dividendos Recebidos",
    "Change In Working Capital": "Mudança no Capital de Giro",
    "Change In Other Current Liabilities": "Mudança em Outros Passivos Correntes",
    "Change In Other Current Assets": "Mudança em Outros Ativos Correntes",
    "Change In Accrued Expense": "Mudança em Despesas a Pagar",
    "Change In Payable": "Mudança em Contas a Pagar",
    "Change In Inventory": "Mudança em Estoques",
    "Change In Receivables": "Mudança em Contas a Receber",
    "Other Non Cash Items": "Outros Itens Não Monetários",
    "Stock Based Compensation": "Compensação Baseada em Ações",
    "Provision and Write Off of Assets": "Provisão e Baixa de Ativos",
    "Deferred Tax": "Imposto Diferido",
    "Depreciation And Amortization": "Depreciação e Amortização",
    "Amortization Cash Flow": "Fluxo de Caixa de Amortização",
}

field_translation_dre = {
    "Total Revenue": "Receita Total",
    "Cost Of Revenue": "Custo da Receita",
    "Gross Profit": "Lucro Bruto",
    "Operating Income": "Lucro Operacional",
    "Interest Expense": "Despesa com Juros",
    "Net Income": "Lucro Líquido",
    "Normalized EBITDA": "EBITDA Normalizado",
    "Total Expenses": "Total de Despesas",
    "Total Operating Income As Reported": "Total de Rendimento Operacional Conforme Relatado",
    "Diluted Average Shares": "Média de Ações Dilutas",
    "Basic Average Shares": "Média de Ações Básicas",
    "Diluted Earnings Per Share": "Lucro por Ação Diluído",
    "Basic Earnings Per Share": "Lucro por Ação Básica",
    "Total Other Income Expense": "Total de Outras Receitas e Despesas",
    "Income Before Tax": "Rendimento Antes do Imposto",
    "Income Tax Expense": "Despesa com Imposto de Renda",
    "Income From Continuing Operations": "Rendimento de Operações Contínuas",
    "Income From Discontinued Operations": "Rendimento de Operações Descontinuadas",
    "Operating Profit": "Lucro Operacional",
    "Operating Expenses": "Despesas Operacionais",
    "Other Income": "Outras Receitas",
    "Other Expense": "Outras Despesas",
    "Research and Development Expenses": "Despesas com Pesquisa e Desenvolvimento",
    "Selling General and Administrative Expenses": "Despesas com Vendas, Gerais e Administrativas",
    "Other Operating Income": "Outras Receitas Operacionais",
    "Depreciation Expense": "Despesa de Depreciação",
    "Amortization Expense": "Despesa de Amortização",
}